version: '3'
services:
  app:
    build: .
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
      - DB_CONEXAO_STRING=mongodb+srv://codebyluck:Y8qSHN65cWaBVpEm@capivaracatalog.rys8d.mongodb.net/
      - SECRET_KEY=capivarasecretkey
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
